version: "3.3"

services:
  
  countriesDB:
    image: postgres:12.1-alpine
    container_name: countriesDB
    restart: unless-stopped
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: appUser
      POSTGRES_PASSWORD: 13
      POSTGRES_DB: countries
      PGDATA: /var/lib/postgresql/pgdata
      TZ: "Europe/Moscow"
  
  mongodb:
    image: mongo:4.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: countries
    ports:
      - 28017:27017
  
  postgres:
    container_name: postgres
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "5429:5432"
    restart: unless-stopped

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8383:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
      
  elasticsearch:
    image: elasticsearch:7.9.2
    ports:
      - '9200:9200'
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: kibana:7.9.2
    ports:
      - '5601:5601'

  logstash:
    image: logstash:7.9.2
    ports:
      - '5000:5000'
    volumes:
      - type: bind
        source: ./logstash_pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true   


  rabbitmq1:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq1
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: appUser
      RABBITMQ_DEFAULT_PASS: 13
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 5673:5672
      - 15673:15672